### ISSUE TITLE
Increase the speed regulation function of the audio player

### ISSUE THREAD

**Issue by CYD1982** [rism-digital/verovio#3285] opened 2023-02-22 07:34 UTC
The current playback volume cannot adjust the bpm, resulting in poor playback effect of some tunes. I hope to increase the speed regulation function

**Comment by ahankinson** [comment] 2023-02-22 07:47
Duplicate of https://github.com/rism-digital/verovio/issues/3246

please see that issue for more information.

**Closed by ahankinson** 2023-02-22 07:47 UTC
Labels: feature request
