### ISSUE TITLE
Rests with location attributes are not transposing

### ISSUE THREAD

**Issue by valeriyvan** [rism-digital/verovio#1521] opened 2020-06-26 10:39 UTC
Transposition doesn't consider overlaps with some elements.

Original mei file https://raw.githubusercontent.com/music-encoding/sample-encodings/master/MEI_4.0/Music/Complete_examples/Chopin_Mazurka.mei

Pages without transposition rendered with command 
`./verovio -r ./data --transpose Chopin_Mazurka.mei -a` and with transposition - `./verovio -r ./data --transpose -F# Chopin_Mazurka.mei -a`.

Rendered pages show that overlaps with tuple number is not considered and overlap with rests become sever:

Page 1 no transposition:
![Chopin_Mazurka_001 no translose svg](https://user-images.githubusercontent.com/1630974/85848399-5ca69b00-b7a9-11ea-8131-dfd3500228df.png)

Page 1 transposition -F#:
![Chopin_Mazurka_001 translose -F# svg](https://user-images.githubusercontent.com/1630974/85848443-6e883e00-b7a9-11ea-8ccf-f28be7a8b619.png)

Page 2 no transposition:
![Chopin_Mazurka_002 no translose svg](https://user-images.githubusercontent.com/1630974/85848484-7e078700-b7a9-11ea-9172-9f303b96dffe.png)

Page 2 transposition -F#:
![Chopin_Mazurka_002 transpose -F# svg](https://user-images.githubusercontent.com/1630974/85848511-8bbd0c80-b7a9-11ea-8d0a-6a3b88ec8c9b.png)

**Comment by craigsapp** [comment] 2020-06-26 18:22
There is a problem with this command (as mentioned in the previous issue):

```bash
./verovio -r ./data --transpose Chopin_Mazurka.mei -a
```

The `--transpose` option takes an argument (operand) which is the transposition amount.  The transposition is therefore `Chopin_Mazurka.mei`.

Also discussed in a previous email, this command has indirect problems:

```
./verovio -r ./data --transpose -F# Chopin_Mazurka.mei -a
```

The key tonic is not encoded in the music (it is found in the header, but this is not checked).  The key signature is `3s` and this is inferred incorrectly by verovio to be A major, then the music is transposed down a minor third based on that assumption.  Therefore the music is not in F# (major or minor), but instead in D# minor.

----------------------

The problem is not that transposition does not consider overlaps, but rather that this is the same as issue #1252:  If there are no explication locations assigned to the rests, it is not the transposer's responsibility to calculate one.  If verovio implements more graceful layer avoidance for rests, this will be less of a problem since most rests should be supplied without positions and vertically placed automatically.

------------------------

However, there is a useful enhancement to add to the transposition of rests.  Currently rests with `@oloc` and `@ploc` are not moved when the music is transposed, but they should.

Here is an example:

<img width="365" alt="Screen Shot 2020-06-26 at 10 36 08 AM" src="https://user-images.githubusercontent.com/3487289/85886224-81474680-b79a-11ea-93c0-13feceb8d7b3.png">


MEI data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2020-06-26T10:35:34" version="3.0.0-dev-4714301-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000000240020914">
    <score xml:id="score-0000001057212532">
     <scoreDef xml:id="scoredef-0000000770103169">
      <staffGrp xml:id="staffgrp-0000000414516605">
       <staffDef xml:id="staffdef-0000000121367962" n="1" lines="5">
        <clef xml:id="clef-0000001771856829" shape="G" line="2" />
        <meterSig xml:id="metersig-L2F1" count="2" unit="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="1">
       <staff xml:id="staff-0000002025098870" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L5F1" dur="4" oct="4" pname="g" accid.ges="n" />
         <note xml:id="note-L6F1" dur="4" oct="4" pname="e" accid.ges="n" />
        </layer>
        <layer xml:id="layer-L5F2N2" n="2">
         <rest xml:id="rest-L5F2" dur="4" ploc="a" oloc="3" />
         <rest xml:id="rest-L6F2" dur="4" ploc="f" oloc="3" />
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

Here is transposition up an octave (transposing by interval rather than key tonic should always work):


```bash
verovio --transpose P8 file.txt -atmei
```

(calling the file `file.txt` so that the output file `file.mei` does not erase the input file).

<img width="333" alt="Screen Shot 2020-06-26 at 10 36 17 AM" src="https://user-images.githubusercontent.com/3487289/85886523-206c3e00-b79b-11ea-8067-d5d7a5cd70bf.png">

The rests stay in place, but ideally they would be move up an octave as well.  This still would not be 100% ideal, since the rests in the second layer should not exceed the middle line of the staff.   So that is why having improved automatic placement of rests is preferred rather than relying on the transposition to transpose always at the same interval as the pitches.

MEI data for transposed score:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2020-06-26T10:35:34" version="3.0.0-dev-4714301-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000000240020914">
    <score xml:id="score-0000001057212532">
     <scoreDef xml:id="scoredef-0000000770103169">
      <staffGrp xml:id="staffgrp-0000000414516605">
       <staffDef xml:id="staffdef-0000000121367962" n="1" lines="5">
        <clef xml:id="clef-0000001771856829" shape="G" line="2" />
        <meterSig xml:id="metersig-L2F1" count="2" unit="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="1">
       <staff xml:id="staff-0000002025098870" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L5F1" dur="4" oct="4" pname="g" accid.ges="n" />
         <note xml:id="note-L6F1" dur="4" oct="4" pname="e" accid.ges="n" />
        </layer>
        <layer xml:id="layer-L5F2N2" n="2">
         <rest xml:id="rest-L5F2" dur="4" ploc="a" oloc="3" />
         <rest xml:id="rest-L6F2" dur="4" ploc="f" oloc="3" />
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

-------------

This should be fairly easy to implement.   If the rest has `rest@ploc` and `rest@oloc`, treat these as `note@pname` and `note@oct`.  With the transposed pitch, throw away the `@accid` information and move the new `note@pname` to `rest@ploc` and also `note@oct` to `rest@oloc`.


If the rest has only `rest@loc` and not `rest@ploc` and `rest@oloc`, then it is almost as easy:

In the Transposer class: https://github.com/rism-ch/verovio/blob/develop/include/vrv/transposition.h
there is a function `GetTranspositionIntervalClass()` that returns the numeric transposition interval.  You can then send this into the `IntervalToDiatonicChromatic()` function to extract the diatonic transposition amount.  This value is the number of lines/spaces that the rest must be adjusted.  So something along the lines of:


```cpp
Transposer transposer;
transposer.SetTransposion("P8");  // transpose up perfect octave
int transval = transposer.GetTranspositionIntervalClass();
int diatonic;
int chromatic;
transposer.IntervalToDiatonicChromatic(diatonic, chromatic, transval);
// now diatonic should be +7 and chromatic should be +12.
```

In this case the diatonic value is 7, meaning the rests should be moved up 7 diatonic steps (7 lines and spaces) so add this value to `rest@loc` to update the rest's position.

I leave implement of these algorithms to the reader 😉

**Closed** 2021-11-24 07:46 UTC
Labels: enhancement
