### ISSUE TITLE
 ClassId for 'xxx' not found

### ISSUE THREAD

**Issue by Duanle** [rism-digital/verovio#3192] opened 2023-01-07 05:31 UTC
**Describe the problem**
After generating SVG for several times with 'svgAdditionalAttribute', this exception will occur

**Verovio information**
 - Version of Verovio [Verovio 3.15.0-dev-920f376]
 - Binding [NDK]

**Environment information (as appropriate)**
 - OS: [android]

**Screenshots**
![WX20230107-130016](https://user-images.githubusercontent.com/6520982/211132772-f5efd269-de99-4bc0-91a8-b1b24801f2be.png)

**Comment by lpugin** [comment] 2023-01-07 18:16
Your description of the problem is not detailed enough and you did not provide input data. I will close the issue unless you make the effort to make the issue understandable and that it can be reproduced.

**Comment by Duanle** [comment] 2023-01-08 06:23
**Describe the problem:**
I call verovio to render svg through jni on an android device. On my android device, this problem is not limited to a certain xml. This problem can occur with every xml. This problem does not occur when I first call 'toolkit. RenderToSVGFile()' for rendering after I start the app and load '. so' lib. However, after several times of rendering (re rendering the current xml or switching xml), this problem occurs. At this time, if I kill the app and restart it, I repeat the process again, which results in no 'dur' tags such as' note 'in svg.
The same version of verovio source code, which I compiled on the Mac, does not have this problem

**This is my jni code:**
`
  
extern "C" JNIEXPORT jobjectArray JNICALL
renderStaffFiles(JNIEnv *env, jobject, jstring jResourcePath, jstring jInputFilePath,jstring jOptionJson) {
    const char *resourcePath = env->GetStringUTFChars(jResourcePath, NULL);
    const char *inputFilePath = env->GetStringUTFChars(jInputFilePath, NULL);
    const char *optionJson = env->GetStringUTFChars(jOptionJson, NULL);

    std::string fileSuffix;
    std::string fileName;
    std::string folderPath;

    getInputFileSuffix(inputFilePath, fileSuffix);
    getInputFileName(inputFilePath, fileName);
    getInputFolderPath(inputFilePath, folderPath);

    vrv::Toolkit toolkit(false);
    toolkit.SetResourcePath(resourcePath);
    toolkit.SetOptions(optionJson);
    toolkit.LoadFile(inputFilePath);

    int count = toolkit.GetPageCount();
    auto jArray = (jobjectArray) env->NewObjectArray(count, env->FindClass("java/lang/String"), env->NewStringUTF(""));

    for (int p = 1; p < count + 1; p++) {
        std::string cur_outfile = fileName;
        cur_outfile += vrv::StringFormat("_%03d", p);
        cur_outfile += ".svg";
        std::string svgPath = vrv::StringFormat("%s%s", folderPath.c_str(), cur_outfile.c_str());
        toolkit.RenderToSVGFile(svgPath, p);
        env->SetObjectArrayElement(jArray, p - 1, env->NewStringUTF(svgPath.c_str()));
    }
    std::string midiPath = vrv::StringFormat("%s%s.mid", folderPath.c_str(), fileName.c_str());
    toolkit.RenderToMIDIFile(midiPath);
    return jArray;
}

`

**This is my musicxml file:**
[Etude_in_C_Minor_Revolutionary.txt](https://github.com/rism-digital/verovio/files/10367813/Etude_in_C_Minor_Revolutionary.txt)

**Comment by Duanle** [comment] 2023-01-08 06:51
> Your description of the problem is not detailed enough and you did not provide input data. I will close the issue unless you make the effort to make the issue understandable and that it can be reproduced.

**Describe the problem:**
I call verovio to render svg through jni on an android device. On my android device, this problem is not limited to a certain xml. This problem can occur with every xml. This problem does not occur when I first call 'toolkit. RenderToSVGFile()' for rendering after I start the app and load '. so' lib. However, after several times of rendering (re rendering the current xml or switching xml), this problem occurs. At this time, if I kill the app and restart it, I repeat the process again, which results in no 'dur' tags such as' note 'in svg.
The same version of verovio source code, which I compiled on the Mac, does not have this problem

**This is my jni code:**
`
  
extern "C" JNIEXPORT jobjectArray JNICALL
renderStaffFiles(JNIEnv *env, jobject, jstring jResourcePath, jstring jInputFilePath,jstring jOptionJson) {
    const char *resourcePath = env->GetStringUTFChars(jResourcePath, NULL);
    const char *inputFilePath = env->GetStringUTFChars(jInputFilePath, NULL);
    const char *optionJson = env->GetStringUTFChars(jOptionJson, NULL);

    std::string fileSuffix;
    std::string fileName;
    std::string folderPath;

    getInputFileSuffix(inputFilePath, fileSuffix);
    getInputFileName(inputFilePath, fileName);
    getInputFolderPath(inputFilePath, folderPath);

    vrv::Toolkit toolkit(false);
    toolkit.SetResourcePath(resourcePath);
    toolkit.SetOptions(optionJson);
    toolkit.LoadFile(inputFilePath);

    int count = toolkit.GetPageCount();
    auto jArray = (jobjectArray) env->NewObjectArray(count, env->FindClass("java/lang/String"), env->NewStringUTF(""));

    for (int p = 1; p < count + 1; p++) {
        std::string cur_outfile = fileName;
        cur_outfile += vrv::StringFormat("_%03d", p);
        cur_outfile += ".svg";
        std::string svgPath = vrv::StringFormat("%s%s", folderPath.c_str(), cur_outfile.c_str());
        toolkit.RenderToSVGFile(svgPath, p);
        env->SetObjectArrayElement(jArray, p - 1, env->NewStringUTF(svgPath.c_str()));
    }
    std::string midiPath = vrv::StringFormat("%s%s.mid", folderPath.c_str(), fileName.c_str());
    toolkit.RenderToMIDIFile(midiPath);
    return jArray;
}

`

**This is my musicxml file:**
[Etude_in_C_Minor_Revolutionary.txt](https://github.com/rism-digital/verovio/files/10367813/Etude_in_C_Minor_Revolutionary.txt)

**Comment by craigsapp** [comment] 2023-01-08 07:37
Maybe all of the tempo changes are related to the problem?

<img width="1128" alt="Screenshot 2023-01-07 at 11 30 19 PM" src="https://user-images.githubusercontent.com/3487289/211185368-40e544b8-4392-49e5-9a0a-579b75ce2632.png">

If you cut the score in half, does the same problem happen (such as measures 1&ndash;40), and if it does, then does measures 1&ndash;20 have the same problem, and if so, then does measures 1&ndash;10 have the same problem, and if so, does measures 1&ndash;5 have the same problem?

Here is another MusicXML file of the same composition:  
[010-1b-Sm-012.txt](https://github.com/rism-digital/verovio/files/10367907/010-1b-Sm-012.txt)

Does this MusicXML file have a similar problem?

**Comment by Duanle** [comment] 2023-01-08 08:01
> Maybe all of the tempo changes are related to the problem?
> 
> <img alt="Screenshot 2023-01-07 at 11 30 19 PM" width="1128" src="https://user-images.githubusercontent.com/3487289/211185368-40e544b8-4392-49e5-9a0a-579b75ce2632.png">
> 
> If you cut the score in half, does the same problem happen (such as measures 1–40), and if it does, then does measures 1–20 have the same problem, and if so, then does measures 1–10 have the same problem, and if so, does measures 1–5 have the same problem?
> 
> Here is another MusicXML file of the same composition: [010-1b-Sm-012.txt](https://github.com/rism-digital/verovio/files/10367907/010-1b-Sm-012.txt)
> 
> Does this MusicXML file have a similar problem?

My other musicxml without beat change also has this problem, so I think this problem should not be caused by the input data. And this problem will occur after repeated generation for several times. I've tried your musicxml, but the problem is still

**Comment by lpugin** [comment] 2023-01-08 12:48
> After generating SVG for several times with 'svgAdditionalAttribute', this exception will occur

1. What are the parameters you are passing to `svgAdditionalAttribute`?
2. Can you confirm that there is no issue without `svgAdditionalAttribute`?

It looks like a memory allocation issue. Maybe this is somewhere else in you program and not in Verovio. It can be in Verovio but you need to narrow the issue down. Use a **minimal** input file that is MEI and not MusicXML and post the complete log file (not an image)

**Comment by Duanle** [comment] 2023-01-08 18:12
> > After generating SVG for several times with 'svgAdditionalAttribute', this exception will occur
> 
> 1. What are the parameters you are passing to `svgAdditionalAttribute`?
> 2. Can you confirm that there is no issue without `svgAdditionalAttribute`?
> 
> It looks like a memory allocation issue. Maybe this is somewhere else in you program and not in Verovio. It can be in Verovio but you need to narrow the issue down. Use a **minimal** input file that is MEI and not MusicXML and post the complete log file (not an image)

I probably know the cause of the problem. As you said, it should be the cause of memory allocation. Because it may take a certain time to render svg, which will cause the main thread to get stuck, so I put verovio on the sub thread to run. So I tried to render svg directly in the main thread. The program did not have exceptions, but I still don't know why this problem occurs in the sub thread. It seems that the code in jni has problems when accessing across threads. I think I can maintain a global 'toolkit' singleton in jni, which can be called across threads in java, so it's probably OK

> > After generating SVG for several times with 'svgAdditionalAttribute', this exception will occur
> 
> 1. What are the parameters you are passing to `svgAdditionalAttribute`?
> 2. Can you confirm that there is no issue without `svgAdditionalAttribute`?
> 
> It looks like a memory allocation issue. Maybe this is somewhere else in you program and not in Verovio. It can be in Verovio but you need to narrow the issue down. Use a **minimal** input file that is MEI and not MusicXML and post the complete log file (not an image)

I probably know the cause of the problem. As you said, it should be the cause of memory allocation. Because it may take a certain time to render svg, which will cause the main thread to get stuck, so I put verovio on the sub thread to run. So I tried to render svg directly in the main thread. The program did not have exceptions, but I still don't know why this problem occurs in the sub thread. It seems that the code in jni has problems when accessing across threads. I think I can maintain a global 'toolkit' singleton in jni, which can be called across threads in java, In this way, there should be no error

**Comment by Duanle** [comment] 2023-01-09 03:42
> > After generating SVG for several times with 'svgAdditionalAttribute', this exception will occur
> 
> 1. What are the parameters you are passing to `svgAdditionalAttribute`?
> 2. Can you confirm that there is no issue without `svgAdditionalAttribute`?
> 
> It looks like a memory allocation issue. Maybe this is somewhere else in you program and not in Verovio. It can be in Verovio but you need to narrow the issue down. Use a **minimal** input file that is MEI and not MusicXML and post the complete log file (not an image)

Is it true that verovio cannot run in a sub thread? I run the svg rendering code in a sub thread on the ios device. The same problem occurs. The tests I tested can be rendered normally in the main process of Android and IOS, and there will be exceptions in the sub threads

**Comment by craigsapp** [comment] 2023-01-09 04:00
Running in a main thread or a subthread should be irrelevant since both are threads.  But it will depend on the language.  I run verovio in a web worker in javascript and there is no problem compared to running in the main thread (and I run in a separate thread from the user interface for the same reason you want to do it in Java).

Perhaps your subthread does not free memory, so it similar to a memory leak?  What is the behavior of rendering a single measure?  Does it  cause problems, and does the problem take longer to occur?

How often are you re-rendering in the subthread?  Are you finishing a rendering before doing another render is started?  Is there more than one instance of verovio running?  Maybe in multiple threads (one instance for each subthread)?  If there are multiple subthreads with multiple verovio instances, how many of them are there?

**Comment by craigsapp** [comment] 2023-01-09 04:25
This discussion may be related (if there are multiple verovio threads): https://github.com/rism-digital/verovio/discussions/3162

**Comment by lpugin** [comment] 2023-01-09 07:17
Could you answer my questions?

> 1. What are the parameters you are passing to svgAdditionalAttribute?
> 2. Can you confirm that there is no issue without svgAdditionalAttribute?

I guess the threading issue comes from the fact that `GetClassId` uses a static member. Setting `s_classIdsRegistry` to `thread_local` should if it.

**Comment by ahankinson** [comment] 2023-01-09 08:18
> It seems that the code in jni has problems when accessing across threads. I think I can maintain a global 'toolkit' singleton in jni, which can be called across threads in java, In this way, there should be no error

I would think you should go the other way -- make sure that all Verovio operations are encapsulated in a single thread (your sub-thread). Sharing the toolkit instance from the main thread to sub-threads is likely to cause problems since Verovio maintains its own internal state, and parallel operations that are unaware of the current internal state of Verovio are likely to enact conflicting operations on the data.

So if your main thread is trying to perform operations on the Verovio toolkit, and is unaware of the fact that the sub-thread is currently busy with an earlier operation, then you're going to get all kinds of weird behaviours.

A pattern I've used before in multi-threaded apps is to treat the Verovio thread as a "rendering server": You give the thread string data, and it responds with the SVG you want some time in the future. This means that the thread operations are completely encapsulated: You define a "getPages(musicxml: string) -> list[string]" operation, where the main thread passes the notation data as a string, and the method returns a list of SVG pages as string data. In the implementation this would delegate the processing to your rendering threads.

The important part is that no operations are able to interrupt Verovio while it's currently engaged in an operation with a given set of data, and you don't assume you know the internal state of the toolkit prior to doing anything with it. Every operation begins with a `loadData` and a `resetOptions`, because you can never really be sure what the previous set of operations was, and thus what the state of the toolkit is.

I think this is probably similar to how @craigsapp is running his web worker.

**Comment by Duanle** [comment] 2023-01-09 09:03
> Could you answer my questions?
> 
> > 1. What are the parameters you are passing to svgAdditionalAttribute?
> > 2. Can you confirm that there is no issue without svgAdditionalAttribute?
> 
> I guess the threading issue comes from the fact that `GetClassId` uses a static member. Setting `s_classIdsRegistry` to `thread_local` should fix it.

1. "'svgAdditionalAttribute':[" +
                    "'note@dur','note@dots','note@grace','note@grace.time'," +
                    "'chord@dur','chord@dots','chord@grace','chord@grace.time'," +
                    "'rest@dur','rest@dots'," +
                    "'fTrem@dur','fTrem@beams'," +
                    "'dot@dur'," +
                    "'space@dur','mSpace@dur'," +
                    "'meterSig@count','meterSig@unit'," +
                    "'measure@left','measure@right'," +
                    "'tuplet@num','tuplet@numbase','tuplet@dur'],"
2.I'm sure there is no problem without 'svgAdditionalAttribute'

**Comment by Duanle** [comment] 2023-01-09 09:12
> My use scene does not require multiple threads to access verovio. I'm sure there is no synchronization problem with my verovio. Every time I render, only one sub thread accesses verovio at the same time, because I do not allow users to do other operations when the sub thread renders the svg, until the current rendering is completed

https://github.com/rism-digital/verovio/issues/3192#issuecomment-1375302538

The same problem occurs when I run a verovio toolkit instance directly in the sub thread in C++

**Comment by Duanle** [comment] 2023-01-09 10:17
> > My use scene does not require multiple threads to access verovio. I'm sure there is no synchronization problem with my verovio. Every time I render, only one sub thread accesses verovio at the same time, because I do not allow users to do other operations when the sub thread renders the svg, until the current rendering is completed
> 
> Based on your description, though, you seem to have at least two threads accessing Verovio: Your main thread, where your toolkit is instantiated, and the sub-thread, to which you pass that toolkit instance and it does the rendering work. Or am I misunderstanding something?
> 
> Sharing memory across threads is tricky. I think that's what @lpugin was talking about when he mentioned the `thread_safe` classid registry.

Yes, it is very difficult to share memory across threads, so I did not instantiate it in the main thread. I instantiated the toolkit in the sub thread. The main thread only loads' so '. I have also tried to create' toolkit 'instances in C++, but there are problems

**Comment by lpugin** [comment] 2023-01-10 08:55
I changed the `ObjectFactory::s_classIdsRegistry` to `static thread_local`. Could you give another try with the develop branch?

**Comment by Duanle** [comment] 2023-01-10 17:49
> I changed the `ObjectFactory::s_classIdsRegistry` to `static thread_local`. Could you give another try with the develop branch?

I tried the latest code on 'develop',your modification doesn't seem to work. The issue still exists.

![WX20230111-013518](https://user-images.githubusercontent.com/6520982/211623528-51b93c2a-3658-453d-a57b-c9bc5f8031a2.png)

**Comment by lpugin** [comment] 2023-01-11 10:14
Could you create a repository with a minimal Android App embedding Verovio and reproducing the problem?

**Comment by Duanle** [comment] 2023-01-12 12:08
> Could you create a repository with a minimal Android App embedding Verovio and reproducing the problem?


Thanks for your help.The problem has been solved. It seems to be the memory allocation problem of Verovio under multiple threads. Is it because Verovio does not support multiple thread access? I use the Rxjava library to schedule threads in Android. I set the subthread to 'single' (Schedulers. single()), and always use the same subthread to render svg. This problem never occurs again.

```
DisposableObserver<String[]> disposableObserver = new DisposableObserver<String[]>() {
            ProgressDialog dialog;
            @Override
            protected void onStart() {
                dialog = new ProgressDialog(MainActivity.this);
                dialog.setMessage("loading...");
                dialog.setCancelable(false);
                dialog.show();
            }

            @Override
            public void onNext(String[] value) {
                dialog.dismiss();
            }

            @Override
            public void onError(Throwable e) {
                dialog.dismiss();
            }

            @Override
            public void onComplete() {
                dialog.dismiss();
            }
        };

        Observable.create((ObservableOnSubscribe<String[]>) e -> {
                    String data = "/storage/emulated/0/Android/data/com.daniel.music/data";
                    String[] svg = VerovioJNI.render(data, xml, VerovioJNI.option);
                    e.onNext(svg);
                    e.onComplete();
                }).subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribeOn(Schedulers.single())//normal
//                .subscribeOn(Schedulers.io())//abnormal
//                .subscribeOn(Schedulers.newThread())//abnormal
                .subscribe(disposableObserver);
```

**Closed** 2023-01-12 12:08 UTC
Labels: enhancement, low priority
