### ISSUE TITLE
Missing Sound Effects When Exporting MIDI Files

### ISSUE THREAD

**Issue by csa8280** [rism-digital/verovio#3770] opened 2024-09-09 07:02 UTC
<img width="861" alt="image" src="https://github.com/user-attachments/assets/0824324c-7ca4-473b-a821-cf1149d79c80">
MusicXml File
[effect.xml.zip](https://github.com/user-attachments/files/16926677/effect.xml.zip)

**Comment by ahankinson** [comment] 2024-09-09 07:03
This is not a helpful issue. You need to supply more information.

Closing.

**Closed by ahankinson** 2024-09-09 07:03 UTC
Labels: feature request

**Comment by ahankinson** [comment] 2024-09-09 07:04
Please do not remove the information from the issue template. Filling in those fields will make it much more likely that your issue is accepted.

**Comment by craigsapp** [comment] 2024-09-09 07:34
This feature request is the same as the recently posted one: https://github.com/rism-digital/verovio/issues/3754

and that one is in turn a duplicate of an older request for same: https://github.com/rism-digital/verovio/issues/1928

So the person who wants it the most can submit a PR that implements them 😉

**Comment by craigsapp** [comment] 2024-09-09 07:55
Not exactly a `won't fix` but rather a long-term `feature request` as it will have to be done eventually.  

Glissando are an exception and would need to make assumptions about the MIDI file (e.g., for orchestral music, only one instrument could be on a MIDI channel to implement the gliss for a single instrument).  Also, the maximum limit for pitch-bend range is two octaves, and this example exceeds that by a fifth.  And a special general MIDI command would need to be added to the MIDI file to change the default of four semitones to 24 for the pitch-bend depth, and the two notes (or chords) would have to be merged into a single note.   So glisses will probably remain `won't fix`.

It would be interesting for you to post a MIDI file export for the example music to see what happens with the glissando in particular.

Why is the trill extension line going over the rest in measure 11?

Arpeggios (third measure) are already implemented.

Staccatos and accents should be relatively easy to implement (divide the duration of the note in half when inserting a staccato note, add 10 to the note velocity for accented notes, +15-20 for the marcato accent perhaps).

**Comment by ahankinson** [comment] 2024-09-09 07:58
I've marked this one won't fix because a) we already have an issue for this, and b) there is not enough details to know what they are asking for.

Any further information should be given on the open issue that you mentioned, just so we can make sure to keep track and not have conversations spread all over the place.

**Comment by craigsapp** [comment] 2024-09-09 08:06
A `wontfix` label will confuse people coming to this page in the future, causing them to think that verovio will never implement ornamentations.  

 Better can be to lock the conversation on this issue:
<img width="296" alt="Screenshot 2024-09-09 at 1 01 03 AM" src="https://github.com/user-attachments/assets/68079d99-8b32-4205-9f03-11e1c3a19806">

I added the same-as issue links on purpose so that all of the issues have cross links to each other.  Then people finding this issue (since it is the most recent and probably at the top of the search results) will know where to add further discussion (particularly if you also lock the conversation for #3754).

**Comment by craigsapp** [comment] 2024-09-09 08:10
But Re: locking, I requested a post of the MIDI rendering of the example score (in the originating software), so not particularly useful to lock at this time, as it does not make sense to post that MIDI file in the earliest related issue.
