### ISSUE TITLE
Humdrum to MEI conversion doesn't pass through Humdrum's fontStyle=italic correctly

### ISSUE THREAD

**Issue by gregchapman-dev** [rism-digital/verovio#3074] opened 2022-10-12 19:12 UTC
**Describe the problem**
In Humdrum files, fontStyle parameters like italic can only be unspecified (false) or specified (true).  When mapping to MEI fontStyle parameters, the choices are: normal, italic, and unspecified (in which case the renderer can pick its own default). (Yes there's also oblique, but Humdrum doesn't support it.)  So there is an interesting 2 choices -> 3 choices mapping problem here.  The same mapping problem occurs for fontWeight.  The current solution for "italic" in iohumdrum.cpp is to map Humdrum's unspecified to FONTSTYLE_normal, and Humdrum's specified (e.g. "!LO:TX:i:con fiero") to MEI's unspecified.  The first choice (unspecified -> normal) seems reasonable, but 'italic' -> 'unspecified' loses really important information (the Humdrum encoder really wanted italics, and that fact is lost).  If Verovio is used to render the resulting MEI file, no-one will notice, of course, since Verovio's renderer defaults to italic text in many cases.  But when other MEI parsers parse such an MEI file (and say, convert it to a music21 score) the subsequent renderer (say, MuseScore or Finale) will be free to render it with whatever their default fontStyle is, and could well get it wrong.  Here is my proposal:

Humdrum italic unspecified -> MEI FONTSTYLE_normal (as before)
Humdrum italic specified -> MEI FONTSTYLE_italic (new behavior: was MEI fontstyle unspecified)
Humdrum bold unspecified -> MEI FONTWEIGHT_normal (new behavior: was MEI fontweight unspecified)*
Humdrum bold specified -> MEI FONTWEIGHT_bold (as before)

(*) I don't care about this case as much, but I like consistency.

**Verovio information**
 - develop
 - command-line

**Environment information (as appropriate)**
 - OS: macOS

**Comment by craigsapp** [comment] 2022-10-12 20:09
> In Humdrum files, fontStyle parameters like italic can only be unspecified (false) or specified (true). When mapping to MEI fontStyle parameters, the choices are: normal, italic, and unspecified (in which case the renderer can pick its own default).

There are no unspecified font stylings in the Humdrum `!LO:TX` parameters.   The default is "normal" rather than "undefined", and then there are booleans to activate italic and/or bold, with unspecified meaning "false":

<img width="966" alt="Screen Shot 2022-10-12 at 12 39 32 PM" src="https://user-images.githubusercontent.com/3487289/195433046-63074374-3d7a-4f91-ae3d-6e5e82b869c5.png">

``` tsv
**kern
=1
!LO:TX:t=plain
1c
=2
!LO:TX:i:t=italic
1d
=3
!LO:TX:B:t=bold
1e
=4
!LO:TX:Bi:t=bold-italic joined
1f
=4
!LO:TX:b:B:i:t=bold-italic separate
1g
=
*-
```

| parameter | meaning |
| --- | --- | 
| _none_    | normal | 
| `i`            | italic     |
| `B`          | bold      |
| `B:i`, `i:B`        | bold-italic |
| `Bi`, `iB`        | bold-italic (convenience parameters that turn on bold and italic at the same time) |


<details>
<summary> Click to view MEI conversion </summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2022-10-12T12:49:07" version="3.13.0-dev-17b50cf">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="m1ke4k5w">
    <score xml:id="s1vub6ao">
     <scoreDef xml:id="suchinw" midi.bpm="400.000000">
      <staffGrp xml:id="s1wbezjx">
       <staffDef xml:id="staffdef-L1F1" n="1" lines="5">
        <clef xml:id="c1q9enzq" shape="G" line="2" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="1">
       <staff xml:id="staff-L1F1" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L4F1" dur="1" oct="4" pname="c" accid.ges="n" />
        </layer>
       </staff>
       <dir xml:id="dir-L3F1" place="above" staff="1" tstamp="1.000000">
        <rend xml:id="rsuqly2" fontstyle="normal">plain</rend>
       </dir>
      </measure>
      <measure xml:id="measure-L5" n="2">
       <staff xml:id="staff-L5F1N1" n="1">
        <layer xml:id="layer-L5F1N1" n="1">
         <note xml:id="note-L7F1" dur="1" oct="4" pname="d" accid.ges="n" />
        </layer>
       </staff>
       <dir xml:id="dir-L6F1" place="above" staff="1" tstamp="1.000000">italic</dir>
      </measure>
      <measure xml:id="measure-L8" n="3">
       <staff xml:id="staff-L8F1N1" n="1">
        <layer xml:id="layer-L8F1N1" n="1">
         <note xml:id="note-L10F1" dur="1" oct="4" pname="e" accid.ges="n" />
        </layer>
       </staff>
       <dir xml:id="dir-L9F1" place="above" staff="1" tstamp="1.000000">
        <rend xml:id="r8a1alc" fontstyle="normal" fontweight="bold">bold</rend>
       </dir>
      </measure>
      <measure xml:id="measure-L11" n="4">
       <staff xml:id="staff-L11F1N1" n="1">
        <layer xml:id="layer-L11F1N1" n="1">
         <note xml:id="note-L13F1" dur="1" oct="4" pname="f" accid.ges="n" />
        </layer>
       </staff>
       <dir xml:id="dir-L12F1" place="above" staff="1" tstamp="1.000000">
        <rend xml:id="r5tom2d" fontweight="bold">bold-italic joined</rend>
       </dir>
      </measure>
      <measure xml:id="measure-L14" n="4">
       <staff xml:id="staff-L14F1N1" n="1">
        <layer xml:id="layer-L14F1N1" n="1">
         <note xml:id="note-L16F1" dur="1" oct="4" pname="g" accid.ges="n" />
        </layer>
       </staff>
       <dir xml:id="dir-L15F1" place="below" staff="1" tstamp="1.000000">
        <rend xml:id="r1ht1t57" fontweight="bold">bold-italic separate</rend>
       </dir>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

</details>


Verovio chooses `rend@fontstyle="italic"` as a default when none is given (while in Humdrum `LO:TX` parameters, the default is `@fontstyle="normal"`.

Here is the italic text in the MEI conversion that you are complaining about:

```xml
       <dir xml:id="dir-L6F1" place="above" staff="1" tstamp="1.000000">italic</dir>
```

I am currently using undefined to select italic in MEI, since that is the default in verovio.  And choosing a default display of italic was probably due to most text directions being displayed in italic, so using italic as the default would minimize the size of the file.

It is perhaps safer to explicitly give `@fontstyle="italic"` for such cases as you mention, so I will make it explicit rather than implicit and no longer hope that the renderer is using italic as the default.

**Comment by craigsapp** [comment] 2022-10-12 20:50
Commit https://github.com/rism-digital/verovio/commit/1b525e9d6c8165aeec0263764b205851a25811ae implements explicit italic font styling in `<dir>` elements:

<img width="964" alt="Screen Shot 2022-10-12 at 1 43 28 PM" src="https://user-images.githubusercontent.com/3487289/195444473-98f698dc-8da3-4444-a920-7bd2cf930485.png">

```tsv
**kern
=1
!LO:TX:t=plain
1c
=2
!LO:TX:i:t=italic
1d
=3
!LO:TX:B:t=bold
1e
=4
!LO:TX:Bi:t=bold-italic joined
1f
=4
!LO:TX:b:B:i:t=bold-italic separate
1g
=
*-
```

<details>
<summary> Click to view MEI conversion </summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title />
         </titleStmt>
         <pubStmt />
      </fileDesc>
      <encodingDesc>
         <appInfo>
            <application isodate="2022-10-12T13:44:16" version="3.13.0-dev-17b50cf">
               <name>Verovio</name>
               <p>Transcoded from Humdrum</p>
            </application>
         </appInfo>
      </encodingDesc>
      <workList>
         <work>
            <title />
         </work>
      </workList>
   </meiHead>
   <music>
      <body>
         <mdiv xml:id="mml5xv1">
            <score xml:id="soq27f1">
               <scoreDef xml:id="stwo10w" midi.bpm="400.000000">
                  <staffGrp xml:id="s18f5emg">
                     <staffDef xml:id="staffdef-L1F1" n="1" lines="5">
                        <clef xml:id="cm4jrfn" shape="G" line="2" />
                     </staffDef>
                  </staffGrp>
               </scoreDef>
               <section xml:id="section-L1F1">
                  <measure xml:id="measure-L1" n="1">
                     <staff xml:id="staff-L1F1" n="1">
                        <layer xml:id="layer-L1F1N1" n="1">
                           <note xml:id="note-L4F1" dur="1" oct="4" pname="c" accid.ges="n" />
                        </layer>
                     </staff>
                     <dir xml:id="dir-L3F1" place="above" staff="1" tstamp="1.000000">
                        <rend xml:id="r16qw42o" fontstyle="normal">plain</rend>
                     </dir>
                  </measure>
                  <measure xml:id="measure-L5" n="2">
                     <staff xml:id="staff-L5F1N1" n="1">
                        <layer xml:id="layer-L5F1N1" n="1">
                           <note xml:id="note-L7F1" dur="1" oct="4" pname="d" accid.ges="n" />
                        </layer>
                     </staff>
                     <dir xml:id="dir-L6F1" place="above" staff="1" tstamp="1.000000">
                        <rend xml:id="rqvc9sb" fontstyle="italic">italic</rend>
                     </dir>
                  </measure>
                  <measure xml:id="measure-L8" n="3">
                     <staff xml:id="staff-L8F1N1" n="1">
                        <layer xml:id="layer-L8F1N1" n="1">
                           <note xml:id="note-L10F1" dur="1" oct="4" pname="e" accid.ges="n" />
                        </layer>
                     </staff>
                     <dir xml:id="dir-L9F1" place="above" staff="1" tstamp="1.000000">
                        <rend xml:id="rj1icro" fontstyle="normal" fontweight="bold">bold</rend>
                     </dir>
                  </measure>
                  <measure xml:id="measure-L11" n="4">
                     <staff xml:id="staff-L11F1N1" n="1">
                        <layer xml:id="layer-L11F1N1" n="1">
                           <note xml:id="note-L13F1" dur="1" oct="4" pname="f" accid.ges="n" />
                        </layer>
                     </staff>
                     <dir xml:id="dir-L12F1" place="above" staff="1" tstamp="1.000000">
                        <rend xml:id="rm6wgll" fontstyle="italic" fontweight="bold">bold-italic joined</rend>
                     </dir>
                  </measure>
                  <measure xml:id="measure-L14" n="4">
                     <staff xml:id="staff-L14F1N1" n="1">
                        <layer xml:id="layer-L14F1N1" n="1">
                           <note xml:id="note-L16F1" dur="1" oct="4" pname="g" accid.ges="n" />
                        </layer>
                     </staff>
                     <dir xml:id="dir-L15F1" place="below" staff="1" tstamp="1.000000">
                        <rend xml:id="r9unx84" fontstyle="italic" fontweight="bold">bold-italic separate</rend>
                     </dir>
                  </measure>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>
```

</details>

The italic text is now encoded explicitly as:

```xml
<dir xml:id="dir-L6F1" place="above" staff="1" tstamp="1.000000">
   <rend xml:id="rqvc9sb" fontstyle="italic">italic</rend>
</dir>
```

**Comment by craigsapp** [comment] 2022-10-12 21:10
There are also tempo markings, where the text does have a concept of undefined when converting to MEI and rendering with verovio:

<img width="1199" alt="Screen Shot 2022-10-12 at 2 00 18 PM" src="https://user-images.githubusercontent.com/3487289/195447470-d573c667-d3e5-45a1-a41f-6d2dc24a8710.png">

```tsv
!!!OMD: Allegro ([quarter]=120)
**kern
*M4/4
=1
4c
4d
4e
4f
=2
!LO:TX:t=[half]=63
*M2/2
2d
2e
=
!LO:TX:i:t=Allegro assai ([quarter-dot]=118)
*M6/8
4.c
4.d
=
*-
```

<details>
<summary> Click to view MEI conversion for above Humdrum data </summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/dev/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="5.0.0-dev">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title />
         </titleStmt>
         <pubStmt />
      </fileDesc>
      <encodingDesc>
         <appInfo>
            <application isodate="2022-10-12T14:03:29" version="3.13.0-dev-17b50cf">
               <name>Verovio</name>
               <p>Transcoded from Humdrum</p>
            </application>
         </appInfo>
      </encodingDesc>
      <workList>
         <work>
            <title />
         </work>
      </workList>
      <extMeta>
         <frames xmlns="http://www.humdrum.org/ns/humxml">
            <metaFrame n="0" token="!!!OMD: Allegro ([quarter]=120)" xml:id="L1">
               <frameInfo>
                  <startTime float="0" />
                  <frameType>reference</frameType>
                  <referenceKey>OMD</referenceKey>
                  <referenceValue>Allegro ([quarter]=120)</referenceValue>
               </frameInfo>
            </metaFrame>
         </frames>
      </extMeta>
   </meiHead>
   <music>
      <body>
         <mdiv xml:id="m1m8l103">
            <score xml:id="s1uq1hdp">
               <scoreDef xml:id="s11v43kh" midi.bpm="192.000000">
                  <staffGrp xml:id="s180edsm">
                     <staffDef xml:id="staffdef-L2F1" n="1" lines="5">
                        <clef xml:id="c1z0wstz" shape="G" line="2" />
                        <meterSig xml:id="metersig-L3F1" count="4" unit="4" />
                     </staffDef>
                  </staffGrp>
               </scoreDef>
               <section xml:id="section-L2F1">
                  <measure xml:id="measure-L1" n="1">
                     <staff xml:id="staff-L2F1" n="1">
                        <layer xml:id="layer-L1F1N1" n="1">
                           <note xml:id="note-L5F1" dur="4" oct="4" pname="c" accid.ges="n" />
                           <note xml:id="note-L6F1" dur="4" oct="4" pname="d" accid.ges="n" />
                           <note xml:id="note-L7F1" dur="4" oct="4" pname="e" accid.ges="n" />
                           <note xml:id="note-L8F1" dur="4" oct="4" pname="f" accid.ges="n" />
                        </layer>
                     </staff>
                     <tempo xml:id="tempo-L1F1" staff="1" tstamp="1.000000">Allegro ( <symbol xml:id="s1w5yq9c" glyph.auth="smufl" glyph.name="metNoteQuarterUp" fontsize="70.00%" /> = 120)</tempo>
                  </measure>
                  <scoreDef xml:id="s1vjby3t">
                     <staffGrp xml:id="s1cl3x">
                        <staffDef xml:id="szuaalf" n="1">
                           <meterSig xml:id="m1ibvj7t" count="2" unit="2" />
                        </staffDef>
                     </staffGrp>
                  </scoreDef>
                  <measure xml:id="measure-L9" n="2">
                     <staff xml:id="staff-L9F1N1" n="1">
                        <layer xml:id="layer-L9F1N1" n="1">
                           <note xml:id="note-L12F1" dur="2" oct="4" pname="d" accid.ges="n" />
                           <note xml:id="note-L13F1" dur="2" oct="4" pname="e" accid.ges="n" />
                        </layer>
                     </staff>
                     <tempo xml:id="tempo-L11F1" place="above" staff="1" tstamp="1.000000">
                        <symbol xml:id="s1h04xbc" glyph.auth="smufl" glyph.name="metNoteHalfUp" fontsize="70.00%" /> = 63</tempo>
                  </measure>
                  <scoreDef xml:id="s1hyo3ur">
                     <staffGrp xml:id="svqlclh">
                        <staffDef xml:id="s54spcu" n="1">
                           <meterSig xml:id="mq4ntk6" count="6" unit="8" />
                        </staffDef>
                     </staffGrp>
                  </scoreDef>
                  <measure xml:id="measure-L14">
                     <staff xml:id="staff-L14F1N1" n="1">
                        <layer xml:id="layer-L14F1N1" n="1">
                           <note xml:id="note-L17F1" dots="1" dur="4" oct="4" pname="c" accid.ges="n" />
                           <note xml:id="note-L18F1" dots="1" dur="4" oct="4" pname="d" accid.ges="n" />
                        </layer>
                     </staff>
                     <tempo xml:id="tempo-L16F1" place="above" staff="1" tstamp="1.000000">Allegro assai ( <symbol xml:id="s12tadb" glyph.auth="smufl" glyph.name="metNoteQuarterUp" fontsize="70.00%" /> <symbol xml:id="sc9mla2" glyph.auth="smufl" glyph.name="metAugmentationDot" fontsize="70.00%" /> = 118)</tempo>
                  </measure>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>
```

</details>

Currently no font stylings/weights are transferred to MEI (notice the italic styling in the third measure is not converted, although that might be a left-over of implicit italics that I have not checked).   Verovio chooses to render `<tempo>` marks as bold-normal.

I have never needed/wanted to change the default styling for tempo markings in verovio, but that could be enhanced if needed.  I would probably handle `LO:TX:` parameters that are mapped to `<tempo>` differently, and need to add a `nobold` option to prevent the display of the tempo marking in bold (but that can be a separate issue).

**Closed by craigsapp** 2022-10-12 21:10 UTC

**Comment by lpugin** [comment] 2022-10-13 06:16
What seems important to me is that if something is unspecified in the file, then it should also remain also unspecified in the MEI. So something like:
* Humdrum bold unspecified -> MEI FONTWEIGHT_normal

does not look optimal to me.

As far as Verovio is concerned, there are obviously some default choices that had to be made. We can certainly think about how these could be changed if this is needed, but this is of course a completely different issue.

**Comment by craigsapp** [comment] 2022-10-13 06:52
The problem is that you chose "italic" as the default fontstyle for MEI `<dir>` (i.e. when fontstyle is undefined), while I choose "normal" as the default for Humdrum `LO:TX`.  Giving the `i` option is required in a `LO:TX` parameter in order to make it italic, and `B` for bold.  If neither `i` or `B` are present, then logically it defaults to the non-italic/non-bold fontface, which in MEI is called "normal".  

So there is no undefined/unspecified fontstyles when coming from Humdrum `LO:TX` parameters into a `<dir>`.   I was previously mapping Humdrum italic to an unspecified `@fontstyle` in MEI since verovio will display that as italic.  But to guarantee expected fontstyle display across multiple renderers (whenever there is another one besides verovio :-), it is better as @gregchapman-dev suggests to explicitly encode with `rend@fontstyle="italic"`  to guarantee that all renderers display the intended italics properly.

If there is documentation in the MEI guidelines for renders that recommends an unspecified fontface for `<dir>` text should map to italic (rather than normal), then maybe it is OK to map italic in Humdrum text to unspecified in MEI `<dir>`.   And of course, explicit italic fontstyle on `<dir>` required a child `<rend>`, which makes the data more difficult to read.  Perhaps allowing font stylings on `<dir>` would be nice, such as `<dir fontstyle="normal">`.

(`<tempo>` is a separate case where I defer to the verovio styling by not currently allowing any font styling from being transmitted from Humdrum.)

**Comment by gregchapman-dev** [comment] 2022-10-13 06:54
I agree in general with your statement about unspecified -> unspecified. But Humdrum doesn't really have an unspecified state for italic and bold. If you don't specify italics (or bold) on, they're off (and that's the only way to specify them off).

**Comment by craigsapp** [comment] 2022-10-13 07:00
> As far as Verovio is concerned, there are obviously some default choices that had to be made. We can certainly think about how these could be changed if this is needed, but this is of course a completely different issue.

No need to change it in verovio.  Most editions of music use italics for `<dir>` so it is reasonable to default to italic style for them.   I decided to require explicit italic on the Humdrum equivalent of `<dir>`, in part because that was how it is set up in some music editors (Finale I think).

**Comment by rettinghaus** [comment] 2022-10-13 07:23
I agree with @lpugin that unspecified should stay that way in conversion to MEI. If you really want to set italics etc. explicitly for displaying purposes you should set `UseGlobalStyling` to false or pass another CSS to `SvgDeviceContext`. 
(MEI is not Verovio and Verovio is not MEI)

**Comment by craigsapp** [comment] 2022-10-13 07:42
>  If you really want to set italics etc. explicitly for displaying purposes you should set UseGlobalStyling to false or pass another CSS to SvgDeviceContext.

Remind me of how to do these?  Leaving italics as an unspecified style but then specifying in the MEI document what the unspecified style should be would be good.
