### ISSUE TITLE
Repeat bars missed in MusicXML conversion

### ISSUE THREAD

**Issue by infojunkie** [rism-digital/verovio#2746] opened 2022-03-30 02:27 UTC
**Describe the problem**
Repeat bars are missed in the attached MusicXML file.

**To Reproduce**
1. Upload the [attached MusicXML file](https://github.com/rism-digital/verovio/files/8376301/salma-ya-salama.zip) to https://www.verovio.org/musicxml.html
2. Click "Convert to MEI"
3. Play it in the MEI viewer
4. Observe that the first section "Intro" only plays once, instead of twice, even though the repeat bars are showing.

**Expected behavior**
The repeat bars should be honored.

**Environment information (as appropriate)**
 - OS: Ubuntu
 - Browser: Chrome

**Screenshots**
![screenshot-www verovio org-2022 03 29-19_23_05](https://user-images.githubusercontent.com/92977/160738632-49f6233e-961f-4552-94a0-5d5c10dbe17e.png)

**Comment by lpugin** [comment] 2022-03-30 05:46
Thanks. If I understand correctly, the issue is about the MIDI output and not about MusicXML import / rendering. In that case, it is a duplicate of https://github.com/rism-digital/verovio/issues/235. Please re-open and comment if not.

**Closed by lpugin** 2022-03-30 05:46 UTC

**Comment by infojunkie** [comment] 2022-03-30 15:30
Yes, looks like the same, thanks.
