### ISSUE TITLE
Hyphens for <syl> from different layers don't position properly.

### ISSUE THREAD

**Issue by earboxer** [rism-digital/verovio#1329] opened 2020-03-04 17:10 UTC
The `syl`s "to!" and "Se" are part of verse 1, but attached to notes in a different layer (this is necessary because verse 1 and 2 have different notes).

The dashes don't connect the correct notes together, as seen in this picture:

<img width="722" alt="music score showing misplaced dashes, arrows pointing them out" src="https://user-images.githubusercontent.com/12452738/75903851-3337bd00-5e10-11ea-990f-89b924bbbc64.png">

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title> Holy, Holy, Holy! Lord God Almighty!</title>
                <respStmt>
                    <persName role="composer">MUSIC (NICAEA 11.12.12.10): John Bacchus Dykes, 1861;</persName>
                    <persName role="poet">TEXT: Reginald Heber, 1827, Spanish trans. Juan B. Cabrera</persName>
                </respStmt>
            </titleStmt>
            <pubStmt></pubStmt>
        </fileDesc>
        <encodingDesc xml:id="encodingdesc-0000000847242407">
            <appInfo xml:id="appinfo-0000001559406742">
                <application xml:id="application-0000001663125439" isodate="2020-03-04T11:52:35" version="2.6.0-dev-34e89bb">
                    <name xml:id="name-0000000739356643">Verovio</name>
                    <p xml:id="p-0000001537681097">Transcoded from MusicXML</p>
                </application>
            </appInfo>
        </encodingDesc>
    </meiHead>
    <music>
        <body>
            <mdiv xml:id="mdiv-0000000517481802">
                <score xml:id="score-0000000743739498">
                    <scoreDef xml:id="scoredef-0000000268420499">
                        <staffGrp xml:id="staffgrp-0000001283065535">
                            <staffDef xml:id="staffdef-0000000295865849" n="1" lines="5" ppq="1" clef.shape="G" clef.line="2" meter.count="4" meter.unit="4">
                                <keySig xml:id="keysig-0000000801667674" mode="major" sig="2s" />
                            </staffDef>
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-0000001527040409">
                        <pb xml:id="pb-0000000898820505" />
                        <measure xml:id="measure-0000001006607717" n="1">
                            <staff xml:id="staff-0000000606994815" n="1">
                                <layer xml:id="layer-0000000758821518" n="1">
                                    <note xml:id="note-0000000023948513" dur.ppq="2" dur="2" oct="4" pname="a" stem.dir="up">
                                        <verse xml:id="verse-0000001429502382" n="1">
                                            <syl xml:id="syl-0000001657796146" con="d" wordpos="i">¡San</syl>
                                        </verse>
                                        <verse xml:id="verse-0000000432482562" n="2">
                                            <syl xml:id="syl-0000000009417432" con="d" wordpos="i">Ho</syl>
                                        </verse>
                                    </note>
                                    <note xml:id="note-0000001744694568" dur.ppq="2" dur="2" oct="4" pname="a" stem.dir="up">
                                        <verse xml:id="verse-0000001776904119" n="2">
                                            <syl xml:id="syl-0000000932079491" con="s" wordpos="t">ly!</syl>
                                        </verse>
                                    </note>
                                </layer>
                                <layer xml:id="layer-0000001253641494" n="2">
                                    <note xml:id="note-0000000930868401" dur.ppq="1" dur="4" oct="4" pname="c" stem.dir="down" accid.ges="s" />
                                    <note xml:id="note-0000000171387721" dur.ppq="1" dur="4" oct="4" pname="e" stem.dir="down" />
                                    <note xml:id="note-0000000228568520" dur.ppq="1" dur="4" oct="4" pname="d" stem.dir="down" />
                                    <note xml:id="note-0000000429173694" dur.ppq="1" dur="4" oct="4" pname="c" stem.dir="down" accid.ges="s" />
                                </layer>
                                <layer xml:id="layer-0000000247541823" n="3">
                                    <space xml:id="space-0000000409146825" dur.ppq="2" dur="2" />
                                    <note xml:id="note-0000001452716708" dur.ppq="1" dur="4" oct="4" pname="a" stem.dir="up">
                                        <verse xml:id="verse-0000001838766750" n="1">
                                            <syl xml:id="syl-0000000715318400" con="s" wordpos="t">to!</syl>
                                        </verse>
                                    </note>
                                    <note xml:id="note-0000001730131989" dur.ppq="1" dur="4" oct="4" pname="a" stem.dir="up">
                                        <verse xml:id="verse-0000001216462096" n="1">
                                            <syl xml:id="syl-0000000266738390" con="d" wordpos="i">Se</syl>
                                        </verse>
                                    </note>
                                </layer>
                            </staff>
                            <slur xml:id="slur-0000001978206175" startid="#note-0000000930868401" endid="#note-0000000171387721" curvedir="below" />
                            <slur xml:id="slur-0000000106061981" startid="#note-0000000228568520" endid="#note-0000000429173694" curvedir="below" />
                        </measure>
                        <measure xml:id="measure-0000000357384313" right="end" n="2">
                            <staff xml:id="staff-0000000030471605" n="1">
                                <layer xml:id="layer-0000000624011194" n="1">
                                    <note xml:id="note-0000000932524270" dur.ppq="1" dur="4" oct="4" pname="b" stem.dir="up">
                                        <verse xml:id="verse-0000000363087274" n="1">
                                            <syl xml:id="syl-0000000311821623" con="s" wordpos="t">ñor</syl>
                                        </verse>
                                        <verse xml:id="verse-0000001691190434" n="2">
                                            <syl xml:id="syl-0000001588000881" con="s">Lord</syl>
                                        </verse>
                                    </note>
                                    <note xml:id="note-0000000081142059" dur.ppq="1" dur="4" oct="4" pname="b" stem.dir="up">
                                        <verse xml:id="verse-0000000878250273" n="1">
                                            <syl xml:id="syl-0000001128385591" con="d" wordpos="i">om</syl>
                                        </verse>
                                    </note>
                                    <note xml:id="note-0000000819168815" dur.ppq="1" dur="4" oct="4" pname="b" stem.dir="up">
                                        <verse xml:id="verse-0000001365235793" n="1">
                                            <syl xml:id="syl-0000001129231001" con="d" wordpos="m">ni</syl>
                                        </verse>
                                        <verse xml:id="verse-0000002031864135" n="2">
                                            <syl xml:id="syl-0000000605334901" con="s">God</syl>
                                        </verse>
                                    </note>
                                    <note xml:id="note-0000001705531341" dur.ppq="1" dur="4" oct="4" pname="b" stem.dir="up">
                                        <verse xml:id="verse-0000001041453861" n="1">
                                            <syl xml:id="syl-0000000617736671" con="d" wordpos="m">po</syl>
                                        </verse>
                                        <verse xml:id="verse-0000001116737942" n="2">
                                            <syl xml:id="syl-0000001995052780" con="d" wordpos="i">al</syl>
                                        </verse>
                                    </note>
                                </layer>
                                <layer xml:id="layer-0000000884398700" n="2">
                                    <note xml:id="note-0000000221350491" dur.ppq="1" dur="4" oct="3" pname="b" stem.dir="down" />
                                    <note xml:id="note-0000000394773907" dur.ppq="1" dur="4" oct="4" pname="c" stem.dir="down" accid.ges="s" />
                                    <note xml:id="note-0000000160464105" dur.ppq="1" dur="4" oct="4" pname="d" stem.dir="down" />
                                    <note xml:id="note-0000000316113135" dur.ppq="1" dur="4" oct="4" pname="e" stem.dir="down" />
                                </layer>
                            </staff>
                            <tie xml:id="tie-0000001811924354" startid="#note-0000000932524270" endid="#note-0000000081142059" />
                            <slur xml:id="slur-0000002033990524" startid="#note-0000000221350491" endid="#note-0000000394773907" curvedir="below" />
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

**Comment by rettinghaus** [comment] 2022-04-13 19:05
I'm not sure that this encoding makes sense. Also I'm wondering why you want to use a different notation in measure one and two. In the second measure this seems to do fine.

**Comment by lpugin** [comment] 2024-12-27 16:00
This is looking like a duplicate of https://github.com/rism-digital/verovio/issues/3843.

**Closed by lpugin** 2024-12-27 16:00 UTC
Labels: enhancement
