### ISSUE TITLE
Clef change at beginning of measure renders strangely

### ISSUE THREAD

**Issue by KunstDerFuge** [rism-digital/verovio#3009] opened 2022-08-30 23:52 UTC
When introducing a clef change on the first beat of a measure, Verovio renders it in a previous measure instead.

**To Reproduce**
Minimal XML file (generated by music21) that demonstrates the behavior is [here](https://gist.github.com/KunstDerFuge/790cc85bd4e2f526100b0a12a2557c83).
When rendered in Verovio, the bass clef, which should appear at the beginning of measure 2, instead appears on the & of beat one in measure one.

![image](https://user-images.githubusercontent.com/19453213/187562434-3aa18639-5164-4405-9362-3c24ca96f8bb.png)

**Expected behavior**
A bass clef should appear at the beginning of measure 2, as happens when the file is rendered with Musescore:

![image](https://user-images.githubusercontent.com/19453213/187562528-dbf8aae7-3d1c-4d7c-9e98-e4d9434dfe76.png)

**Input data**
MusicXML for this example is available [in this gist](https://gist.github.com/KunstDerFuge/790cc85bd4e2f526100b0a12a2557c83).

**Verovio information**
 - Verovio 3.9.0
 - Javascript version

The problem can also be observed when uploading this file on the [Verovio website's MusicXML viewer](https://www.verovio.org/musicxml.html).

**Environment information (as appropriate)**
 - OS: Linux (Manjaro)
 - Firefox

**Additional info**
This behavior does not happen when the time signature is changed, e.g. to 6/4 (so that the new clef no longer falls on the first beat of a new measure), or when the new clef is moved to the next or previous eighth note.

**Comment by rettinghaus** [comment] 2022-08-31 08:20
This is interesting, because the cause of this is the insane value of divisions. If you use a small value here, everything works as expected. There seems to be a miscalculation happening.

**Comment by craigsapp** [comment] 2022-08-31 08:58
This is the standard number of divisions for MusicXML files created with Music21.

The reason is that the prime factors of 10080  are 2, 2, 2, 2, 2, 3, 3, 5, 7

So in other words this number handles tuplets up to 7, and durations down to 128th notes.

There are only quarter notes 10080 and eighth notes 5040 with no round-off errors in the file, so it should be expected that the MusicXML-to-MEI converter handles them properly.

**Comment by rettinghaus** [comment] 2022-08-31 09:19
It was indeed a hard coded value. Should be fixed with #3010.

**Closed** 2022-08-31 10:17 UTC
Labels: musicxml
